import {Cavaet} from "next/font/google";
export const metadata = {
    title: "Next.js Course",
    description: "Generated by Next.js",
  };

  import Script from "next/script";


  const CavaetFont = Cavaet({weight:["400","700"], subsets:["latin"]});

  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body>
          {children}
        </body>
        <Script src="https://cdn.jsdelivr.net/npm/darkmode-js@1.5.7/lib/darkmode-js.min.js"></Script >
      </html>
    );
  }