import Header from "@/components/header/header";
import "../styles/home.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="dark-bg">
        <Header />
        {children}
      </body>
    </html>
  );
}
