export const metadata = {
  title: "Dashboard",
  description: "Generated by Next.js",
  authors: [{ name: "Seb" }, { name: "Pierre" }],
};

function page() {
  return <div>Page</div>;
}

export default page;
