export const metadata = {
  title: "Dashboard",
  description: "Generated by Next.js",
  authors: [{ name: "Seb" }, { name: "Pierre" }],
};

function page() {
  return <div>
    <h1 style={{marginTop:"50px"}}>Dashboard Page</h1>
    <div className="part-yellow" id="yellow"></div>
    <div className="part-green" id="green"></div>
    <div className="part-red" id="red"></div>
  </div>;
}

export default page;
